### ISSUE TITLE
Categories not displaying

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-next#74] opened 2021-05-05 09:43 UTC
![image.png](https://images.zenhubusercontent.com/5807a7a095e42b6c5baabbd3/36b27657-61d0-4fe7-b4d1-624ebbc1e51e)

**Comment by mateodaza** [comment] 2021-06-28 20:05
I'll close this as I don't believe it's happening anymore / can't reproduce

**Closed by mateodaza** 2021-06-28 20:05 UTC
