### ISSUE TITLE
implement mobile menu

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-next#554] opened 2021-12-18 16:04 UTC

**Comment by divine-comedian** [comment] 2021-12-21 18:46
testing on next.giveth.io with metamask mobile browser

I load up the site and I see the lines on the left indicating a drop down menu i can sign in and successfully navigate to other pages . ( community, projects, giveconomy, home) 

however once signed in the regular drop down menu when I click on my account portrait is impossible to access... 
![Screenshot_20211221-124350.png](https://user-images.githubusercontent.com/67759413/146982159-794991da-c53d-4d5c-9c52-db06dbf20d56.png)

when I try to scroll the drop down menu it only scrolls the page behind it - moving this back to in progress!

**Comment by divine-comedian** [comment] 2021-12-21 18:49
not sure who is picking up the flag on this one @MoeNick , I tagged @mateodaza

**Comment by mateodaza** [comment] 2021-12-21 18:50
> not sure who is picking up the flag on this one @MoeNick , I tagged @mateodaza

I'm merging all the updates from @RamRamez and whatever is missing I'll take it

**Comment by MoeNick** [comment] 2021-12-21 18:51
We decided to revert it to be just responsive. The design is not confirmed yet so now you can test it again.

**Comment by MoeNick** [comment] 2021-12-22 11:46
@divine-comedian would you pls confirm?

**Comment by divine-comedian** [comment] 2021-12-22 16:58
testing again on next.giveth.io with metamask browser - this update now we can no longer easily navigate to /join /projects or the giveconomy . the drop down menu works fine and everything

![Screenshot_20211222-104955.png](https://user-images.githubusercontent.com/67759413/147127699-f79008d3-ba72-4ade-be63-b5aea830e199.png)

sometimes however it takes two taps to open the drop down menu - the GIV token tracker when we click it, it links to the GIVeconomy and opens the tooltip - it should just show the tooltip.

 perhaps we could add another row to the navbar on mobile that shows the 4 options on the desktop navbar (Community, GIVeconomy, Projects, Home). this second column dissapears when user scrolls down and reappears when user scrolls up

@MoeNick  what do you think?

**Comment by divine-comedian** [comment] 2021-12-22 17:01
example: 
![image](https://user-images.githubusercontent.com/67759413/147128699-e9d874cd-0bcb-4734-84af-cca4a3cf5b9a.png)
the drop down menu on the user account would flow over top of this second row..

**Comment by MoeNick** [comment] 2021-12-22 17:03
No sorry we implement it and revert  it several times. It needs mobile view to get finilize

**Comment by divine-comedian** [comment] 2021-12-22 17:05
okay so this issue is on hold for now? can you move it to the appropriate pipeline

**Comment by mateodaza** [comment] 2021-12-23 18:19
![Screen_Shot_2021-12-23_at_4 44 16_PM](https://user-images.githubusercontent.com/18689480/147278431-20f81dd3-1a8c-4ec9-ad04-f802ffe70c14.png)
Implementing this for launch. Already live

**Comment by divine-comedian** [comment] 2021-12-24 20:08
testing on metamask browser mobile - I'm having a lot of difficulty navigating using the drop down menu - it often takes several clicks or page refreshes to get it to open to show the menu. could it be site traffic? it seems very erratic

**Comment by mateodaza** [comment] 2022-02-09 19:26
closing this because mobile support will be taken care on v2 version

**Closed by mateodaza** 2022-02-09 19:26 UTC
