### ISSUE TITLE
Integrate backend sorting, filtering and pagination on donations and projects

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-next#319] opened 2021-10-18 23:27 UTC

**Comment by mohammadranjbarz** [comment] 2021-11-07 06:46
@divine-comedian 
Before this PR the front end was fetching all projects from server then sort them and do al the things locally, but now it's all on the server side ( it have lots of performances when our projects count increases), so for testing this you should pay attention to these items:
- [ ] Sort by `Hearts` 
- [ ] Sort by `Quality Score`
- [ ] Sort by `Amount Raised`
- [ ] Sort by `CreationDate` `ASC`
- [ ]  Sort by `CreationDate` `DESC`
- [ ] Filter by `Verified` 
- [ ] Search projects ( Search with `title`, `description`, `impactLocation`)
- [ ] Pagination

@CarlosQ96  @RamRamez Add more items if you think check list is not completed

**Comment by divine-comedian** [comment] 2021-11-07 16:30
> @divine-comedian Before this PR the front end was fetching all projects from server then sort them and do al the things locally, but now it's all on the server side ( it have lots of performances when our projects count increases), so for testing this you should pay attention to these items:
> 
> * [ ]  Sort by `Hearts`
> * [ ]  Sort by `Quality Score`
> * [ ]  Sort by `Amount Raised`
> * [ ]  Sort by `CreationDate` `ASC`
> * [ ]   Sort by `CreationDate` `DESC`
> * [ ]  Filter by `Verified`
> * [ ]  Search projects ( Search with `title`, `description`, `impactLocation`)
> * [ ]  Pagination
> 
> @CarlosQ96 @RamRamez Add more items if you think check list is not completed

I have to raise a flag immediately since that we've chosen to not explicitly explain Quality Score (to prevent gamification) we should not have `Quality Score` as the displayed option to sort a project by. from my understanding this was `Default` before.

**Comment by mohammadranjbarz** [comment] 2021-11-07 17:00
> > @divine-comedian Before this PR the front end was fetching all projects from server then sort them and do al the things locally, but now it's all on the server side ( it have lots of performances when our projects count increases), so for testing this you should pay attention to these items:
> > 
> > * [ ]   Sort by `Hearts`
> > * [ ]   Sort by `Quality Score`
> > * [ ]   Sort by `Amount Raised`
> > * [ ]   Sort by `CreationDate` `ASC`
> > * [ ]    Sort by `CreationDate` `DESC`
> > * [ ]   Filter by `Verified`
> > * [ ]   Search projects ( Search with `title`, `description`, `impactLocation`)
> > * [ ]   Pagination
> > 
> > @CarlosQ96 @RamRamez Add more items if you think check list is not completed
> 
> I have to raise a flag immediately since that we've chosen to not explicitly explain Quality Score (to prevent gamification) we should not have `Quality Score` as the displayed option to sort a project by. from my understanding this was `Default` before.

@RamRamez 
Could you show it `Default` in the frontend but when sending to backend send QualityScore instead of that, in this way there is no need to change backend

**Comment by divine-comedian** [comment] 2021-11-07 17:04
@mohammadranjbarz @RamRamez 

I'm just about done testing and will have much more feedack before you begin implementing changes

**Comment by divine-comedian** [comment] 2021-11-07 17:12
okay testing on `next.giveth.io` 

clean cache and cookies 

Looks like the basic functionality of the sorting works - hearts, donation raised, creation date.. etc.. 

I did notice however now we only show 2 rows of projects per page, this seems very limited and we did implement the 'endless scroll' feature a while ago and now it seems to be removed. I would strongly advocate for bringing it back or greatly increases the number of projects shown on each page. 

replace the text for `Quality Score` with `Default` as mentioned 
also for Creation Date titles are not quite intuitive for non technical users, I would change to something more explicit - 

Date Created - Ascending
Date Created - Descending

I also see we created a new drop down menu for `filter by` I think this makes the UI a bit busier and less intuitive. We could simply remove the drop down menu and add `Verified` and `Traceable` to the `sort by` drop down menu while giving it the same `filter` functionality when selected

To that point as well I cannot see the `Traceable` filter on the UI, was that removed for a reason?

**Comment by mohammadranjbarz** [comment] 2021-11-07 17:22
> okay testing on `next.giveth.io`
> 
> clean cache and cookies
> 
> Looks like the basic functionality of the sorting works - hearts, donation raised, creation date.. etc..
> 
> I did notice however now we only show 2 rows of projects per page, this seems very limited and we did implement the 'endless scroll' feature a while ago and now it seems to be removed. I would strongly advocate for bringing it back or greatly increases the number of projects shown on each page.
> 
> replace the text for `Quality Score` with `Default` as mentioned also for Creation Date titles are not quite intuitive for non technical users, I would change to something more explicit -
> 
> Date Created - Ascending Date Created - Descending
> 
> I also see we created a new drop down menu for `filter by` I think this makes the UI a bit busier and less intuitive. We could simply remove the drop down menu and add `Verified` and `Traceable` to the `sort by` drop down menu while giving it the same `filter` functionality when selected
> 
> To that point as well I cannot see the `Traceable` filter on the UI, was that removed for a reason?

About bringing back `Verified` to sort, I thinks it's better to see https://github.com/Giveth/giveth-next/issues/373
@MoeNick  What do you think?

about `Traceable` I think you are right we should show them ( it needed some backend job, because we don't want to call it from frontend like before.

**Comment by RamRamez** [comment] 2021-11-07 17:30
> > > @divine-comedian Before this PR the front end was fetching all projects from server then sort them and do al the things locally, but now it's all on the server side ( it have lots of performances when our projects count increases), so for testing this you should pay attention to these items:
> > > 
> > > * [ ]    Sort by `Hearts`
> > > * [ ]    Sort by `Quality Score`
> > > * [ ]    Sort by `Amount Raised`
> > > * [ ]    Sort by `CreationDate` `ASC`
> > > * [ ]     Sort by `CreationDate` `DESC`
> > > * [ ]    Filter by `Verified`
> > > * [ ]    Search projects ( Search with `title`, `description`, `impactLocation`)
> > > * [ ]    Pagination
> > > 
> > > @CarlosQ96 @RamRamez Add more items if you think check list is not completed
> > 
> > 
> > I have to raise a flag immediately since that we've chosen to not explicitly explain Quality Score (to prevent gamification) we should not have `Quality Score` as the displayed option to sort a project by. from my understanding this was `Default` before.
> 
> @RamRamez Could you show it `Default` in the frontend but when sending to backend send QualityScore instead of that, in this way there is no need to change backend

Yes, I'll fix it.

**Comment by RamRamez** [comment] 2021-11-08 21:47
> > @divine-comedian Before this PR the front end was fetching all projects from server then sort them and do al the things locally, but now it's all on the server side ( it have lots of performances when our projects count increases), so for testing this you should pay attention to these items:
> > 
> > * [ ]   Sort by `Hearts`
> > * [ ]   Sort by `Quality Score`
> > * [ ]   Sort by `Amount Raised`
> > * [ ]   Sort by `CreationDate` `ASC`
> > * [ ]    Sort by `CreationDate` `DESC`
> > * [ ]   Filter by `Verified`
> > * [ ]   Search projects ( Search with `title`, `description`, `impactLocation`)
> > * [ ]   Pagination
> > 
> > @CarlosQ96 @RamRamez Add more items if you think check list is not completed
> 
> I have to raise a flag immediately since that we've chosen to not explicitly explain Quality Score (to prevent gamification) we should not have `Quality Score` as the displayed option to sort a project by. from my understanding this was `Default` before.

It's resolved in the new design

**Comment by RamRamez** [comment] 2021-11-08 21:50
> okay testing on `next.giveth.io`
> 
> clean cache and cookies
> 
> Looks like the basic functionality of the sorting works - hearts, donation raised, creation date.. etc..
> 
> I did notice however now we only show 2 rows of projects per page, this seems very limited and we did implement the 'endless scroll' feature a while ago and now it seems to be removed. I would strongly advocate for bringing it back or greatly increases the number of projects shown on each page.
> 
> replace the text for `Quality Score` with `Default` as mentioned also for Creation Date titles are not quite intuitive for non technical users, I would change to something more explicit -
> 
> Date Created - Ascending Date Created - Descending
> 
> I also see we created a new drop down menu for `filter by` I think this makes the UI a bit busier and less intuitive. We could simply remove the drop down menu and add `Verified` and `Traceable` to the `sort by` drop down menu while giving it the same `filter` functionality when selected
> 
> To that point as well I cannot see the `Traceable` filter on the UI, was that removed for a reason?

They are also done in the new design
BTW, I still doubt about putting filter by `verified` and `traceable` in the sort by category

**Comment by DonnaOftadeh** [comment] 2021-11-16 13:53
@mohammadranjbarz @mateodaza I just try to test another thing and encountered this little pagination bug: I searched a project which is unlisted and it shows the pagination without showing the project:
![image](https://user-images.githubusercontent.com/53400757/141997840-236118c8-095d-483a-9916-cfb599e5f4c6.png)

**Comment by mohammadranjbarz** [comment] 2021-11-16 14:24
> @mohammadranjbarz @mateodaza I just try to test another thing and encountered this little pagination bug: I searched a project which is unlisted and it shows the pagination without showing the project: ![image](https://user-images.githubusercontent.com/53400757/141997840-236118c8-095d-483a-9916-cfb599e5f4c6.png)

@CarlosQ96 
Could you take a look on this? I think maybe it's related to search and pagination query

**Comment by CarlosQ96** [comment] 2021-11-16 14:32
@mohammadranjbarz on it! It's probably related to the total Count that typeorm returns.

**Comment by DonnaOftadeh** [comment] 2021-11-18 14:01
@RamRamez dear Ramin, should I test all the items in this PR or wait for the new design to be implemented?

**Comment by RamRamez** [comment] 2021-11-18 15:06
@DonnaOftadeh Please check this in our new App [(https://typescript.giveth.io/projects)](https://typescript.giveth.io/projects)

**Comment by DonnaOftadeh** [comment] 2021-11-22 16:36
@RamRamez I am trying to test sort by various sections  but all it seems Al of the project have the same amount raised (200 dollars), no pagination only load more option, hearts seems working (UI is broken as we are migration to typescript and it needs to be implemented), all of them created 5 days ago so I cannot test the creation date sorting. And for sorting based on verification it behaves a bit weird: We have trace projects sorted as verified and a project in the middle of the pile of projects as verified:
![image](https://user-images.githubusercontent.com/53400757/142899421-eb0ced6e-3ff8-42cd-920a-4e4ae3be8914.png)
Should I test it later? it seems not ready for testing

**Comment by RamRamez** [comment] 2021-11-23 10:29
@DonnaOftadeh:

Total amount raised is now implemented in backend and I added to the UI in PR #[17](https://github.com/Giveth/giveth-io-typescript/pull/17) and now it shows the correct value.

No pagination and now we have load more in new design. You can test this instead.

Sorting and search is buggy from backend and @CarlosQ96 is working on it.

Last updated is not implemented yet in backend and @CarlosQ96 is working on it.

You can't test sorting by creation date since it's not shown in project card.

@DonnaOftadeh Please wait for backend to merge then you can test.

**Comment by MoeNick** [comment] 2021-11-23 10:30
we created #424 for testing it on new ui. 
@DonnaOftadeh pls split-up th issues which ramin said.

**Comment by RamRamez** [comment] 2021-12-06 11:47
> okay testing on `next.giveth.io`
> 
> clean cache and cookies
> 
> Looks like the basic functionality of the sorting works - hearts, donation raised, creation date.. etc..
> 
> I did notice however now we only show 2 rows of projects per page, this seems very limited and we did implement the 'endless scroll' feature a while ago and now it seems to be removed. I would strongly advocate for bringing it back or greatly increases the number of projects shown on each page.
> 
> replace the text for `Quality Score` with `Default` as mentioned also for Creation Date titles are not quite intuitive for non technical users, I would change to something more explicit -
> 
> Date Created - Ascending Date Created - Descending
> 
> I also see we created a new drop down menu for `filter by` I think this makes the UI a bit busier and less intuitive. We could simply remove the drop down menu and add `Verified` and `Traceable` to the `sort by` drop down menu while giving it the same `filter` functionality when selected
> 
> To that point as well I cannot see the `Traceable` filter on the UI, was that removed for a reason?

Fixed in PR #449

**Comment by MoeNick** [comment] 2021-12-09 23:02
@RamRamez I need a confirmation on nextjs version, is it ok?

**Comment by RamRamez** [comment] 2021-12-09 23:28
> 

Confirmed (still we need to remove pagination and add load more).

**Closed** 2021-12-09 23:28 UTC
Labels: next sprint?
